name: bicep

on:
  push:
    branches:
      - 'main'
    tags:
      - development

env:
  ENVIRONMENT: 'dev'

permissions:
  id-token: write
  contents: read

jobs: 
  provision-infra:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}          
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy Bicep'
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters dbAdminPassword=${{ secrets.DB_ADMIN_PASSWORD }}
